; Listing generated by Microsoft (R) Optimizing Compiler Version 19.20.27508.1 

include listing.inc

INCLUDELIB OLDNAMES

PUBLIC	?mean_v@Stats@@QEAANXZ				; Stats::mean_v
PUBLIC	?only_integers@Stats@@QEBA_NXZ			; Stats::only_integers
PUBLIC	?kurtosis@Stats@@QEBANXZ			; Stats::kurtosis
PUBLIC	?mean@Stats@@QEBANXZ				; Stats::mean
PUBLIC	?push@Stats@@QEAAXN@Z				; Stats::push
PUBLIC	?push_v@Stats@@QEAAXU__m256d@@@Z		; Stats::push_v
PUBLIC	?clear@Stats@@QEAAXXZ				; Stats::clear
;	COMDAT pdata
pdata	SEGMENT
$pdata$?mean_v@Stats@@QEAANXZ DD imagerel $LN16@mean_v
	DD	imagerel $LN16@mean_v+102
	DD	imagerel $unwind$?mean_v@Stats@@QEAANXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?push@Stats@@QEAAXN@Z DD imagerel $LN10@push
	DD	imagerel $LN10@push+333
	DD	imagerel $unwind$?push@Stats@@QEAAXN@Z
;	COMDAT xdata
xdata	SEGMENT
$unwind$?push@Stats@@QEAAXN@Z DD 052c01H
	DD	0782cH
	DD	016827H
	DD	04204H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?mean_v@Stats@@QEAANXZ DD 011319H
	DD	06204H
	DD	imagerel __GSHandlerCheck
	DD	020H
END
